### PR TITLE
chore(project): add the .gitignore file to project

### PR DESCRIPTION
**Pull request by xcaspar**

### CODE REVIEW

**Comment by xcaspar** [comment]
@wu-sheng Very strange, I have modified user.name to xcaspar, I will check again.

**Comment by xcaspar** [comment]
@wu-sheng I have changed the name. Thank you.

**Comment by ascrutae** [comment]
releate: #174

**Comment by wu-sheng** [comment]
cc @ascrutae @pengys5 . LGTM, we merge this in 3.0.1 or wait for 3.1?

+1 on 3.1

**Comment by ascrutae** [comment]
+1 on 3.1

**Comment by pengys5** [comment]
+1 on 3.1

**Comment by wu-sheng** [comment]
@xcaspar I will merge this after 3.0.1 released.

**Comment by wu-sheng** [comment]
@xcaspar merging

**Comment by xcaspar** [comment]
@wu-sheng Thank you.

**Comment by wu-sheng** [comment]
@xcaspar Welcome to contribute new features, e.g. new supported plugins or any others

**Comment by xcaspar** [comment]
@wu-sheng OK :-)

**Pull request merged**
