### PR TITLE
chore(collector): add a check for process id in startup script

### PR DESCRIPTION
**Pull request by xcaspar**
#180 
Very sorry to submit the PR so late. I add a simple check for the process in `collector-service.sh`.

### CODE REVIEW

**Comment by ascrutae** [comment]
In my mind, Check action need to execute before execute java command.

**Comment by xcaspar** [comment]
@ascrutae why? The process is created by the java process, so it can only be checked after the java command.

**Comment by wu-sheng** [comment]
> In my opinion, the check action need to execute before executing java command.

@ascrutae `Before` means run `java -version` to check the JRE version? Otherwise, how is this possible?

**Comment by xcaspar** [comment]
@pengys5 OK.

**Comment by ascrutae** [comment]
@xcaspar  I think I maybe miss you mind.  my purpose is that checking the previous pid of collector before start collector.

**Comment by wu-sheng** [comment]
@ascrutae Do you proposal to do the running status checking?

**Comment by ascrutae** [comment]
@wu-sheng  Yes.  that is my mind

**Pull request merged**
