### PR TITLE
add auto local jar file installation before compile

### PR DESCRIPTION
**Pull request by clevertension**
add auto local jar file installation before compile

### CODE REVIEW

**Comment by wu-sheng** [comment]
Thanks for your contributions. I suggest you remove the prepare stage in `.travis.yml`, because you have done this through pom.

**Remove these lines**
```yml
install:
  - cd ci-dependencies
  - mvn install:install-file  -Dfile=jmxtools-1.2.1.jar  -DgroupId=com.sun.jdmk  -DartifactId=jmxtools -Dversion=1.2.1 -Dpackaging=jar
  - mvn install:install-file  -Dfile=jmxri-1.2.1.jar  -DgroupId=com.sun.jmx  -DartifactId=jmxri -Dversion=1.2.1 -Dpackaging=jar
  - mvn install:install-file  -Dfile=dubbox-2.8.4.jar  -DgroupId=com.alibaba  -DartifactId=dubbox -Dversion=2.8.4 -Dpackaging=jar
  - mvn install:install-file  -Dfile=ojdbc14-10.2.0.4.0.jar  -DgroupId=com.oracle  -DartifactId=ojdbc14 -Dversion=10.2.0.4.0 -Dpackaging=jar
  - mvn install:install-file  -Dfile=resin-4.0.41.jar  -DgroupId=com.caucho  -DartifactId=resin -Dversion=4.0.41 -Dpackaging=jar
  - cd ..
```

**Comment by clevertension** [comment]
done!

**Comment by wu-sheng** [comment]
@clevertension Since I have approved this pr and prepare to merge, so you will be a contributor of skywalking project. If you want to add yourself in the contributors list of README, feel free for yourself.  If so,  send a separated pr about adding your name, github account, company(optional) into README.md and README_ZH.md.

**Comment by wu-sheng** [comment]
cc @ascrutae @pengys5

**Pull request merged**
