### PR TITLE
Prototype codes of supporting leaf span

### PR DESCRIPTION
**Pull request by wu-sheng**

### CODE REVIEW

**Comment by wu-sheng** [comment]
Resolve #198

**Comment by wu-sheng** [comment]
What happens on server side?  I can guess the point, but do you have any real cases?

**Comment by ascrutae** [comment]
For example Dubbox provide service by tomcat/jetty. so should we ignore the tomcat component or not?

**Comment by wu-sheng** [comment]
If we do this, we must provide `provider` span. But these is a problem, which one should we keep in segment, first or last ? I assume IT is hard to tell.

**Comment by ascrutae** [comment]
Each plug-in knows whether or not it is the leaf span. and The span generated by each RPC plug-in is peer to peer, one span generate in client side and it must generate one in server side，So we can know span before generate in server side should be ignore or not.

**Comment by wu-sheng** [comment]
Leaf concept don't match the server side. The root  span or some child are service provider, but other child are not. How can you ignore the spans?

**Comment by wu-sheng** [comment]
> For example Dubbox provide service by tomcat/jetty. Should we ignore the tomcat component or not?

Let's discuss on this case. How does the tomcat plugin know these is dubbox component? As you known, Tomcat provide service first, then dubbox. If we want to ignore tomcat, we must do this in the dubbox component. Do you agree?

If yes, at that moment, tomcat plugin's beforeInvoke  has already finished, so `span` and its tags have been generated, and stored in memory. Even we can ignore the tomcat plugin span, the improvement focuses on the cost of network/collector-side, right?

If you agree all of these, we are on the same page. Do you have any proposal about how to ignore the tomcat span, when the dubbox span started? IMO, my only thought is getting the prev span in active-span-stack.

**Comment by ascrutae** [comment]
I agree with you. this question you talking about is how to determine the start time of dubbox component. IMO, we can pop the span that generate before dubbo  component when dubbox component finish.

BTW, the same question also happen in RPC client.

**Comment by wu-sheng** [comment]
The `pop` operation will trigger bad things. Because after dubbox component finished, Tomcat plugin afterInvoke will invoke, if you pop the stack, this must throw an exception.

**Pull request merged**
