### PR TITLE
Provide a new id generation and serialization mechanism

### PR DESCRIPTION
**Pull request by wu-sheng**
Use three long to represent the trace segment id, and global trace id.

This is the official comments:
* Generate a new id, combined by three long numbers.

1. The first one represents application instance id. (most likely just an integer value, would be helpful in protobuf)
1. The second one represents thread id. (most likely just an integer value, would be helpful in protobuf)
1. The third one also has two parts
     1. a timestamp, measured in milliseconds
     2. a seq, in current thread, between 0(included) and 9999(included)

### CODE REVIEW

**Comment by wu-sheng** [comment]
## Background story
In the prev edition, traceSegmentId or globalTrace is combined by these parts:
1. 2 bytes, **type**:  T/S (1 char)
1. 26 bytes, **timestamp**, e.g. 1500598177046, (13 chars)
1. 20 bytes, **UUID hashcode**, e.g. 1186075790, (10 chars)
1. 2 - 10 bytes, ** thread id**, most likely between 1 and 99999, (1 - 5 chars)
1. 2 - 22 bytes, ** thread seq**,  between -2147483648 and 2147483647. (1 - 11 chars)

So the ids used 52 - 80 bytes for each one.

cc @hanahmily

**Comment by wu-sheng** [comment]
cc @liuchang0403

**Comment by wu-sheng** [comment]
## New ID since 3.2
1. Application instance id, Allocated by collector, @pengys5 . Most likely a short or integer is enough. Let's do the math. First we assume that the backend allocates new id with no reuse mechanism. Even we have 1,000 applications, each one of them has (avg) 50 instances, there cost 50, 000 application ids in every reboot. Reboot the cluster in every two days, (either excellent DevOps team or disaster product), the max application instance id is 18,250,000 ( Far from MAX_INT, 2,147,483,647 ). 
1.  Thread id. Allocated by JVM, in theory, it could be a very big int, but actually, if you application is high performance, most likely you use a thread pool, instead of creating thread everyone. So in this case, the id will not be too large. most likely between 1 and 99999, ( A short only )
1. timestamp + [0-9999] seq, definitely a long.

So in protobuf, the id is 1 short/int + 1 short + 1 long, which is 24 bytes. Much less than before.

And in cross-process propagation, mostly HTTP head, we use BASE64 for each part of id. 
1. '#' + 4 chars for short
1. '$' + 8 chars for int
1. 12 chars for long

So the id in BASE64 used 26 or 28 chars.

**Comment by wu-sheng** [comment]
cc @ascrutae

**Comment by hanahmily** [comment]
Time may not be strictly monotonic, e.g. due to adjustments to correct clock drift. It is necessary to  save the latest generation time to prevent the clock from returning to the past is

**Comment by liuchang0403** [comment]
ok i will deal it

**Comment by wu-sheng** [comment]
@hanahmily Thank you for your suggestion. We will add **time-shift-back** recognition mechanism, if we found the **time-shift-back** happened, we do a greater range time shift, in order to make sure the repeated timestamp is harmless.

e.g. the Ops shifts back time to 5 seconds ago, the agent recognize it immediately( right? ), the agent will set the timestamp to 10 years ago, clearly no harm. 

With the time going, 5 seconds passed, the agent recovery to use the real timestamp.

Does this seem good enough for you?

cc @pengys5 @ascrutae

**Pull request merged**
