### PR TITLE
Support Xmemcached v2.x"

### PR DESCRIPTION
**Pull request by IluckySi**
Hi, my friend:
I add a new plugin about {com.googlecode.xmemcached}.
But there is a problem when you use it. threre are two reasons for the problem:
1. https://github.com/killme2008/xmemcached/pull/64
2. https://github.com/raphw/byte-buddy/issues/347

If you want to use this plugin right now, there are two way:
1. You can recompile  {https://github.com/killme2008/xmemcached}, and use the master branch.
The master branch have alreday been modifyed. Or wait the new release version.
2. You also can wait byte-buddy team to fix it, I have already give a issue to byte-buddy team.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@IluckySi Thanks for your contribution first. Because of this possible byte-buddy bug. We can't merge or release this right now. These left us two choices:

1. xmemcached released a new version, we only support that.
1. byte-buddy support this, and we can release this. The best choice. @raphw Hope you can solve this for us.

So sorry for that, I only can keep this pr open, and wait for what is going to happen.

**Comment by wu-sheng** [comment]
And @IluckySi , in this pr. You must provide these in the pr.

1. A simple application includes how are you using the library you instrument, source code repository is fine.
1. Screenshot for trace stack.
1. Screenshot for the Topological graph.  From this, you can see, you miss an icon for memcached in UI repository. You should send a linked pr.

**Comment by IluckySi** [comment]
I can provide an application about xmemcached, but I'm only a java coder, so can't provide an icon about memcahe!

**Comment by wu-sheng** [comment]
@IluckySi You can ask @ascrutae for help, he know some PhotoShop guys.

**Comment by wu-sheng** [comment]
Hi, @IluckySi , as you can see, https://github.com/raphw/byte-buddy/issues/347#issuecomment-333947157 has been confirmed and fixed. So, it will release in 1.7.6 . 

Welcome you to work on this plugin after 1.7.6 released.

**Comment by wu-sheng** [comment]
Since this pr can't be opened again. So I submit #488 to keep things in the loop.

**Pull request closed without merging**
