### PR TITLE
fix Illegal group reference

### PR DESCRIPTION
**Pull request by clevertension**
fix Illegal group reference

### CODE REVIEW

**Comment by wu-sheng** [comment]
@clevertension Maybe add some test cases about `^`, `~` etc, in cases for other unexpected situation?

**Comment by clevertension** [comment]
image

done!

**Comment by wu-sheng** [comment]
cc @ascrutae I am merge this fix.

**Comment by ascrutae** [comment]
OK, This PR look good to me.

**Comment by wu-sheng** [comment]
cc @nsspw  You just need to edit one row to fix this issue.

**Pull request merged**
