### PR TITLE
Improving agent

### PR DESCRIPTION
**Pull request by wu-sheng**
~~This pull request is working in progress.~~

Right now, I intend to improve the agent in these ways:
1. Remove the three maps of tag. This is be benifit for reducing cost and gc.
1. Ignore request with certain suffix, such as: .css, .js, .png, etc.
1. (Uncerntain yet)Adjust sampling mechanism for better performance. The new is: all segments are sampled, which changes to unsampled, iff 1) sampling is on, and first time trigger sample mechanism, 2) at least one extract completed or tag a span as client, 3) no segment-refs.

### CODE REVIEW

**Comment by wu-sheng** [comment]
cc @ascrutae @pengys5 You can review this pr at any time.

**Comment by wu-sheng** [comment]
Finished ~~1.Remove the three maps of tag. This is be benifit for reducing cost and gc.~~

**Comment by wu-sheng** [comment]
1. Remove the “apm-trace” module, isolate the trace structure between agent and collector for considering performance.
2. Change the head name.
3. Provide potienal mechanism for ignore trace with certain suffix.

**Comment by wu-sheng** [comment]
I will provide mechanism to ignore these suffix, `.jpg,.jpeg,.js,.css,.png,.bmp,.gif,.ico,.mp3,.mp4,.html`. Have any suggestion?

cc @sky-walking/team-member @TravelEngineers

**Comment by wu-sheng** [comment]
cc @pengys5 @ascrutae @bai-yang

**Comment by TravelEngineers** [comment]
@wu-sheng  .html这个可以灵活配置就好了。因为有些地方可能存在伪静态的情况。

**Comment by wu-sheng** [comment]
@TravelEngineers 这里提供是默认配置，所有配置都可以通过sky-walking.conf配置文件复写。参考：https://github.com/wu-sheng/sky-walking/wiki/sky-walking-config-file-walkthrough

不过我依然希望可以提供尽可能完备的列表。

**Comment by TravelEngineers** [comment]
@wu-sheng 这样的话，就没什么问题了。你列出的那几类，基本上已经是常用的静态资源了。

**Comment by wu-sheng** [comment]
In this week, I change a lot of agent codes, refactor actually, as a result, sky-walking agent can ignore and sample trace in high performance. Also, it provided the mechanism to support analytic trace in the further.

These are new features:
1. Remove the three maps of tag. This is be benifit for reducing cost and gc.
1. Ignore request with certain suffix, such as: .css, .js, .png, etc.
1. Adjust sampling mechanism for better performance. The new is: all segments are sampled, which changes to unsampled, iff 1) sampling is on, 2) no segment-refs, 3) can't get the sampling factor. When this trace status changes to **unsampled**, the context switch to **IgnoredTracerContext**, which will provide higher performance.

**Comment by wu-sheng** [comment]
@ascrutae @pengys5 You can review this pr now. This is a major improvement in 3.2

**Pull request merged**
